// import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import  ButtonSendTransaction from '../components/ButtonSendTransaction'
import  RegistrationCard from '../components/RegistrationCard'



const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      



      {/* <ButtonSendTransaction/> */}
      <RegistrationCard/>

        
      
    </div>
  );
};

export default Home;
